project:
  type: website
  
website:
  title: "ISSS608-VAA-GroupProject"
  favicon: images/favicon/favicon-96x96.png
  page-navigation: true
  navbar: 
    logo: images/Logo2.png
    title: false
    collapse-below: lg
    search: true
    right:
      - href: about.qmd
        text: About
      - text: "Project Poster"
        #href: Overview/Overview.html
      - text: "Shiny App"
        menu:
          - text: "ShinyApp"
            href: https://johsuanh.shinyapps.io/WeatherOrNot/
          - text: "User Guide"
            #href: ShinyApp/User_Guide.html
      - text: "Team"
        menu:
          - text: "Project Proporsal"
            href: Team/Project_Proposal.html
          - text: "Meeting Records"
            #href: Team/Meeting_Records.html

      
format:
  html:
    toc: true
    toc-location: right
    theme: 
      - theme.scss
    highlight-style: tango
    code-copy: hover
    code-overflow: wrap

editor: visual