---
title: "Data_Preprocessing"
format: html
---

## Load Packages

```{r}
pacman::p_load(sf, tmap, tidyverse,readxl,urca,tseries,plotly,ggdist,ggridges,lubridate,knitr,zoo)
```

## Import Geospatial Data

```{r}
mpsz <- st_read(dsn = "data/geospatial", 
                layer = "MP14_PLNG_AREA_WEB_PL")
```

## Import Weather Data

```{r}
station<-read_csv("data/Singapore_daily_records.csv")
```

```{r}
str(station)
```

Check missing values

```{r}
kable(data.frame(Column = names(station), NAs = colSums(is.na(station))))

```

```{r}
station$mean_temperature_c <- coalesce(station$mean_temperature_c, station$mean_temperature_a_c)
station$maximum_temperature_c <- coalesce(station$maximum_temperature_c, station$maximum_temperature_a_c)
station$minimum_temperature_c <- coalesce(station$minimum_temperature_c, station$minimum_temperature_a_c)


```

```{r}
station <- station %>%
  mutate(across(
    c(highest_30_min_rainfall_mm, highest_60_min_rainfall_mm, highest_120_min_rainfall_mm,
      daily_rainfall_total_mm, mean_temperature_c, maximum_temperature_c, 
      minimum_temperature_c, mean_wind_speed_km_h, max_wind_speed_km_h),
    ~ as.numeric(gsub("\u0097", NA, .))
  )) %>%
  mutate(station = as.factor(station)) %>%
  mutate(
    highest_30_min_rainfall_mm = ifelse(daily_rainfall_total_mm == 0 & is.na(highest_30_min_rainfall_mm), 0, highest_30_min_rainfall_mm),
    highest_60_min_rainfall_mm = ifelse(daily_rainfall_total_mm == 0 & is.na(highest_60_min_rainfall_mm), 0, highest_60_min_rainfall_mm),
    highest_120_min_rainfall_mm = ifelse(daily_rainfall_total_mm == 0 & is.na(highest_120_min_rainfall_mm), 0, highest_120_min_rainfall_mm))

```

```{r}
station <- station %>% 
  select(-c("mean_temperature_a_c", 
            "maximum_temperature_a_c", "minimum_temperature_a_c"))
```

```{r}
kable(data.frame(Column = names(station), NAs = colSums(is.na(station))))

```

```{r}
str(station)
```

## Data Preparation

```{r}
station <- station %>%
  mutate(date = ymd(paste(year, month, day, sep = "-")),
         weekday = wday(date, label = TRUE, abbr = TRUE))
```

Impute missing value with MA-3

```{r}
station$mean_temperature_c <- ifelse(is.na(station$mean_temperature_c),
                                   round(rollapply(station$mean_temperature_c, 
                                                   width = 30,FUN = mean, fill = NA,
                                                   na.rm = TRUE),2),
                                   round((station$minimum_temperature_c+station$maximum_temperature_c)/2,2))
station$mean_wind_speed_km_h <- ifelse(is.na(station$mean_wind_speed_km_h),
                                   round(rollapply(station$mean_wind_speed_km_h, width = 30,
                                             FUN = mean, fill = NA, align = "center",na.rm = TRUE),2),
                                   station$mean_wind_speed_km_h)
station$daily_rainfall_total_mm <- ifelse(is.na(station$daily_rainfall_total_mm),
                                   round(rollapply(station$daily_rainfall_total_mm,width = 30,
                                             FUN = mean, fill = NA, align = "center",na.rm = TRUE),2),
                                   station$daily_rainfall_total_mm)
```

```{r}
station_filtered <- station %>%
  filter(is.na(mean_temperature_c))
```

```{r}
saveRDS(station, "station_data.rds")
```
